dictionary = {
"Building"       : "建筑",
"Food"            : "食物",
"Historical"      : "历史的",
"Industrial"      : "工业的",
"Interior"        : "室内的",
"Nature"          : "自然得",
"Props"           : "道具",
"Street"          : "街道",
"Aquatic"         : "水生植物",
"Climber"         : "攀爬物",
"Crop"            : "农作物",
"Fern"            : "蕨类植物",
"Flowering_Plant" : "有花的植物",
"Garden_Plant"    : "花园植物",
"Grass"           : "草",
"Ground_Cover"    : "地衣",
"Herb"            : "草本植物",
"Houseplant"      : "室内盆栽植物",
"Shrub"           : "灌木",
"Succulent"        : "多肉植物",
"Weed"             : "杂草",
"Asphalt"          : "沥青",
"Bark"             : "树皮",
"Branch"           : "树枝",
"Brick"            : "砖块",
"Coal"             : "煤",
"Concrete"         : "水泥/混凝土",
"Debris"           : "碎块",
"Fabric"           : "纤维",
"Gravel"           : "沙砾",
"Ground"           : "地面",
"Marble"           : "大理石",
"Metal"           : "金属",
"Moss"            : "苔藓",
"Plaster"         : "灰泥",
"Rock"            : "岩石",
"Roofing"         : "屋顶",
"Sand"            : "沙子",
"Snow"            : "雪",
"Soil"            : "土壤",
"Stone"           : "石头",
"Tile"            : "瓷砖",
"Wood"            : "木材",
"Other"           : "其他",
"Blood"           : "血",
"Commercial"      : "商业的",
"Door"            : "门",
"Graffiti"        : "涂鸦",
"Leakage"         : "泄露",
"Mud"             : "泥土",
"Tree"            : "树",
"Trim"            : "修剪",
"Vegetation"       : "植被",
"Fresh_Water"      : "淡水",
"Ocean"            : "海洋",
"Plant"            : "植物",
"Vine"             : "藤蔓",
"Damage"           : "破坏",
"Dirt"             : "脏污",
"Fingerprint"      : "指纹",
"Frost"            : "森林",
"Grain"            : "谷物",
"Grunge"           : "垃圾",
"Rubber"           : "橡胶",
"Stain"            : "污渍",
"Wipe_Mark"        : "擦拭痕迹",
"Imprint"          : "印记",
"Scorch_Mark"      : "烧焦痕迹",
"Spatter"          : "溅",
"Sponge"           : "海绵",
"Traditional"      : "传统的",
"Home"             : "主页",
"Import"           : "导入",
"Settings"         : "设置",
"Notice:"          : "注意:",
"Export successful":"导出成功",
"Error:"           : "错误:",
"Export failed"    : "导出失败",
"Export":"导出",
"Import Settings":"导入设置",
"Name":"名称",
"Type":"类型",
"Category":"分类",
"Subcategory":"子类型",
"Surface Size":"面积",
"Tiles Vertically":"垂直重复",
"Tiles Horizontically":"水平重复",
"Mesh":"网格",
"Preview Image":"预览图",
"ASSETS":"资产",
"Tags":"标签",
"Path Settings":"路径设置",
"Choose folder":"设置目录",
"Remote Library Directory":"远程库目录",
"Connect address":"连接地址",
"Connect port":"连接端口",
'notice:':"注意",
"current settings is saved":"当前的设置已经保存",
"Connect Settings":"连接设置",
"Balcony" : "阳台",
"Beam" : "横梁",
"Combined" : "组和",
"Door" : "门",
"Pillar" : "柱子",
"Railing" : "栏杆",
"Relief" : "浮雕",
"Roof" : "屋顶",
"Roof_Tile" : "瓦片",
"Stair" : "楼梯",
"Trim" : "修剪",
"Wall" : "墙",
"Window" : "窗户",
"Baked_Goods" : "烘焙视频",
"Fruit" : "水果",
"Meat" : "肉",
"Mushroom" : "蘑菇",
"Nut" : "坚果",
"Vegetable" : "蔬菜",
"Feudal_Japan" : "日本古代",
"Medieval" : "中世纪",
"Roman_Empire" : "罗马帝国",
"Wild_West" : "西部",
"Construction" : "建筑物",
"Hardware" : "硬件",
"Mining" : "矿物",
"Railway" : "铁路",
"Storage" : "仓库",
"Ceiling" : "吊顶",
"Decoration" : "装饰",
"Fireplace" : "壁炉",
"Furniture" : "家具",
"Bone" : "骨",
"Debris" : "残骸",
"Embankment" : "路堤",
"Rock" : "岩石",
"Seabed" : "海底",
"Snow" : "雪",
"Tree" : "树",
"Books" : "书籍",
"Farm" : "农场",
"Firewood" : "柴火",
"Military" : "军用物品",
"Palisade" : "栅栏",
"Recreational" : "休闲娱乐",
"Trash" : "垃圾",
"Weaponry" : "武器",
"Wheel" : "轮子",
"Wood" : "木材",
"Barrier" : "路障",
"Bollard" : "柱子",
"Curb" : "马路",
"Highway" : "公路",
"Props" : "道具",
"Sidewalk" : "人行道",
"Traffic_Cone" : "交通标识",
"Floating" : "漂流物",
"Shore" : "海岸",
"Submerged" : "水下",
"Grass" : "草",
"Plant" : "植物",
"Flowerhead" : "花朵",
"Infloresence" : "花类",
"Bush" : "灌木",
"Flowering" : "开花",
"Flowerless" : "无花",
"Lawn" : "草坪",
"Wild" : "野生",
"Forest" : "森林",
"Meadow" : "草地",
"Sandy" : "沙地",
"Urban" : "城市",
"Fine" : "高质量",
"Rough" : "粗糙的",
"Torn" : "撕裂",
"Beech" : "山毛榉树",
"Birch" : "白桦树" ,
"Oak" : "橡树",
"Other" : "其他",
"Plam" : "矿区",
"Pine" : "松树",
"Spruce" : "云杉树",
"Willow" : "柳树",
"Alder" : "赤杨树",
"Juniper" : "杜松树",
"Modern" : "现代",
"Mortar" : "水泥",
"Painted" : "油漆",
"Brick" : "砖",
"Cast_in_Situ" : "铸造现场",
"Damaged" : "损坏",
"Dirty" : "肮脏",
"Slab" : "板材",
"Smooth" : "光滑",
"Nature" : "自然",
"Carpet" : "地毯",
"Leather" : "皮革",
"Pattern" : "图案",
"Plain" : "编织",
"Tarp" : "油布",
"Artificial" : "人造",
"Dried" : "干燥",
"Patchy" : "补丁",
"Natural" : "天然",
"Pebbledash" : "卵石",
"Jungle" : "丛林",
"Roots" : "根",
"Asian" : "亚裔",
"Middle_Eastern" : "中东",
"Roman" : "罗马",
"Polished" : "抛光",
"Tile" : "瓷砖",
"Bare" : "荒芜",
"Corroded" : "侵蚀",
"Corrugated" : "波纹",
"Gun" : "枪",
"Sheet" : "床单",
"Treated" : "治疗",
"Ground" : "地面",
"Fresh" : "新的",
"Old" : "旧的",
"Cliff" : "悬崖",
"Jagged" : "不规整",
"Lava" : "熔岩",
"Mossy" : "青苔",
"New" : "新",
"Beach" : "海滩",
"Desert" : "沙漠",
"Mixed" : "混合",
"Pure" : "干净",
"Clay" : "黏土",
"Mud" : "泥",
"Mulch" : "覆盖",
"Castle" : "城堡",
"Cobblestone" : "鹅卵石",
"Floor" : "地板",
"Granite" : "花岗岩",
"Limestone" : "石灰岩",
"Mosaic" : "马赛克",
"Pebble" : "石子",
"Terrazzo" : "水磨石",
"Ceramic" : "陶瓷",
"Grout" : "泥浆",
"Pavestone" : "铺路石",
"Stone" : "石头",
"Board" : "平台",
"Log" : "原木",
"Parquet" : "复合地板",
"Plank" : "厚木板",
"Veneer" : "胶合板",
"Climber" : "攀登",
"Creature" : "生物",
"Dirt_Road" : "土路",
"Edible" : "食物",
"Fur" : "毛皮",
"Paper" : "纸张",
"Various" : "多彩",
"Spatter" : "飞溅",
"Stain" : "污渍",
"Poster" : "海报",
"Sticker" : "贴纸",
"Crack" : "裂纹",
"Damage" : "损坏",
"Patch" : "修补",
"Ash" : "废墟",
"Burnt" : "烧伤",
"Dirt" : "污物",
"Metal" : "金属",
"Rag" : "破布",
"Rug" : "地毯",
"Stamp" : "印记",
"Tileable" : "平铺的",
"Manhole_Cover" : "井盖",
"Scrap" : "碎物",
"Welding_Seam" : "焊接接缝",
"Spanish" : "西班牙",
"Antique" : "古董",
"Painted_line" : "彩绘线条",
"Porhole" : "孔",
"Bark" : "树皮",
"Branch" : "树枝",
"Flower" : "花",
"Hay" : "干草",
"Leaf" : "叶",
"Twig" : "细枝",
"Vine" : "藤",
"Weed" : "杂草",
"Belt" : "皮带",
"Table_Mat" : "桌垫",
"Stem" : "茎",
"Needle" : "针",
"Assorted_Plant" : "配套工厂",
"Painting" : "绘画",
"Clean" : "无污染",
"Scratched" : "划伤",
"The current Settings have been saved and will take effect after the restart":"当前的设置已经保存,将在重启后生效",
"Asset":"资产",
"is imported":"导入完成",
"Favorite":"最爱",
"Decal" : "贴花",
"Plant" : "植物",
"3D Assets":"3D 资产",
"Surface":"表面"
}
class Translator:
    def tra(self,text:str):
        try:
            return dictionary[text]
        except:
            return text
